apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
- name: cluster
  required: true
  targetType: landscaper.gardener.cloud/kubernetes-cluster

- name: lssComponentDescriptor
  type: componentDescriptorList
  required: false

- name: cloudProfile
  schema:
    type: object
    properties:
      # data from landscape-*-setup/export/kubernetes/KUBERNETES_VERSIONS.yaml
      # versions of item with name 'aws'
      kubernetesVersions:
        type: array
      machineImages:
        type: data
        schema:
          $ref: "cd://component/componentReferences/machine-images/resources/machine-images-schema"
      machineImagesLs:
        type: data
        schema:
          $ref: "cd://component/componentReferences/machine-images/resources/machine-images-schema"
      machineImagesProviderLs:
        type: data
        schema:
          $ref: "cd://component/componentReferences/machine-images/resources/machine-images-schema"
      disableMachineImages:
        type: array
        items:
          type: string
      includeFilters:
        type: array
        items:
          type: string
      excludeFilters:
        type: array
        items:
          type: string
      regions:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            zones:
              type: array

# data from landscape-*-setup/landscape.yaml section gardener-extension-provider-aws.values
- name: controllerRegistration
  schema:
    type: object
    properties:
      concurrentSyncs:
        type: integer
      controllerResources:
        type: array
        items:
          type: object
          properties:
            kind:
              type: string
            type:
              type: string
      resources:
        type: object
        properties:
          requests:
            type: object
            properties:
              cpu:
                type: string
              memory:
                type: string
          limits:
            type: object
            properties:
              cpu:
                type: string
              memory:
                type: string
      vpa:
        scheme:
          type: object

- name: imageVectorOverwrite
  schema:
    type: object
    properties:
      images:
        type: array
        items:
          type: object

exports: []

exportExecutions: []

subinstallations: []

deployExecutions:
- file: /deploy-execution-manifests.yaml
  name: manifests
  type: GoTemplate
