apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
- name: cluster
  required: true
  targetType: landscaper.gardener.cloud/kubernetes-cluster

- name: lssComponentDescriptor
  type: componentDescriptorList
  required: false

- name: cloudProfile
  schema:
    type: object
    properties:
      machineImages:
        type: data
        schema:
          $ref: "cd://component/componentReferences/machine-images/resources/machine-images-schema"
      machineImagesLs:
        type: data
        schema:
          $ref: "cd://component/componentReferences/machine-images/resources/machine-images-schema"
      machineImagesProviderLs:
        type: data
        schema:
          $ref: "cd://component/componentReferences/machine-images/resources/machine-images-schema"
      disableMachineImages:
        type: array
        items:
          type: string
      includeFilters:
        type: array
        items:
          type: string
      excludeFilters:
        type: array
        items:
          type: string
      regions:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            zones:
              type: array

# data from landscape-*-setup/export/kubernetes/KUBERNETES_VERSIONS.yaml
# versions of item with name 'aws'
- name: kubernetesVersions
  schema:
    type: array

# data from landscape-*-setup/landscape.yaml section gardener-extension-provider-aws.values
- name: controllerRegistration
  type: data
  schema:
    $ref: "cd://resources/controller-registration-schema"

- name: dataWhichHasToBePreprocessed
  schema:
    type:object

exports: []

exportExecutions: []

subinstallations:
  - file: /subinst-preprocess-data.yaml

subinstallationExecutions:
- name: subinst-machine-images
  type: GoTemplate
  file: /subinst-machine-images.yaml
- name: subinst-aws-extension
  type: GoTemplate
  file: /subinst-aws-extension.yaml
