apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
- name: cluster
  required: true
  targetType: landscaper.gardener.cloud/kubernetes-cluster

- name: lssComponentDescriptor
  type: componentDescriptorList
  required: false

- name: cloudProfile
  schema:
    type: object
    properties:
      kubernetesVersions:
        type: array
      machineImages:
        type: data
        schema:
          $ref: "cd://component/componentReferences/machine-images/resources/machine-images-schema"
      regions:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            zones:
              type: array

- name: controllerRegistration
  type: data
  schema:
    $ref: "cd://resources/controller-registration-schema"

exports: []

exportExecutions: []

subinstallations: []

deployExecutions:
- file: /deploy-execution-manifests.yaml
  name: manifests
  type: GoTemplate
